# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Playlist_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'playlist_entries',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('lyrics', models.CharField(blank=True, max_length=16384)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Artist')),
                ('genres', models.ManyToManyField(to='rooms.Genre')),
            ],
            options={
                'db_table': 'tracks',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='playlist_tracks',
            field=models.ManyToManyField(through='rooms.Playlist_entry', to='rooms.Track'),
        ),
        migrations.AddField(
            model_name='playlist_entry',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room'),
        ),
        migrations.AddField(
            model_name='playlist_entry',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Track'),
        ),
    ]
