# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist_track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Artist')),
                ('genre', models.ManyToManyField(to='rooms.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='playlist_tracks',
            field=models.ManyToManyField(through='rooms.Playlist_track', to='rooms.Track'),
        ),
        migrations.AddField(
            model_name='playlist_track',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room'),
        ),
        migrations.AddField(
            model_name='playlist_track',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Track'),
        ),
    ]
