# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_track_lyrics'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artist',
            table='artists',
        ),
        migrations.AlterModelTable(
            name='genre',
            table='genres',
        ),
        migrations.AlterModelTable(
            name='playlist_track',
            table='playlist_tracks',
        ),
        migrations.AlterModelTable(
            name='room',
            table='rooms',
        ),
        migrations.AlterModelTable(
            name='track',
            table='tracks',
        ),
    ]
