# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20171031_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='lyrics',
            field=models.CharField(blank=True, max_length=16384),
        ),
        migrations.AlterModelTable(
            name='playlist_entry',
            table='playlist_entry',
        ),
    ]
